### ISSUE TITLE
Create Domain Entities for `pebble`application

### ISSUE THREAD

**Issue by ArnaudJalbert** [ArnaudJalbert/pebble#2]
# TODO

- [ ] Design the entities and objects that will be used in the app.
- [ ] Describe the relationship between them.
- [ ] Define the attributes each have and how they are used.

# Acceptance Criteria

- Detailed design plan is provided
- Each entity is implemented
- Each entity is tested
